spring:
  application:
    name: dax-pay
  profiles:
    active: dev
  config:
    use-legacy-processing: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  thymeleaf:
    mode: LEGACYHTML5
  flyway:
    # 默认不启用
    enabled: false
    # 对特殊占位符不进行替换
    placeholder-replacement: false
# mp配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    banner: false
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: ASSIGN_ID
# 安全框架配置
sa-token:
  is-print: false
  token-name: AccessToken
