spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          # Postgresql连接
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://postgresql:5432/dax-pay-single?serverTimezone=Asia/Shanghai&autoReconnect=true&reWriteBatchedInserts=true
          username: bootx
          password: bootx123
          # MySQL连接
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://mysql:3306/dax-pay-single?serverTimezone=GMT%2B8&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
#          username: root
#          password: bootx123
      hikari:
        keepalive-time: 300000
  data:
    redis:
      host: redis
      port: 6379
      database: 5
      password: bootx123
      lettuce:
        pool:
          max-wait: 1000ms
# 开发时显示debug日志 org.dromara.daxpay
logging:
  level:
    cn.bootx.**: debug
    org.dromara.**: debug
    org.springframework.jdbc.core: debug
# 接口文档配置
springdoc:
  # 默认展开对象类型的属性, 主要用在get类型的参数中
  default-flat-param-object: true
# 基础脚手架配置
bootx-platform:
  common:
    # swagger相关配置
    swagger:
      author: DaxPay
      title: 开源支付平台-单商户服务端
      description: 开源支付平台-单商户服务端
      version: 0.0.1
      base-packages:
        "[BootxPlatform接口]":
          - cn.bootx.platform.common
          - cn.bootx.platform.starter
          - cn.bootx.platform.iam
          - cn.bootx.platform.baseapi
          - cn.bootx.platform.notice
        "[支付管理平台接口]":
          - org.dromara.daxpay
  starter:
    auth:
      enable-admin: true
      ignore-urls:
        - '/actuator/**'
        - '/v3/api-docs/**'
        - '/doc.html'
        - '/swagger-resources/**'
        - '/token/**'
        - '/ws/**'
        - '/demo/**'
        - '/test/**'
        - '/webjars/**'
        - '/web/**'
        - '/h5/**'
        - '/css/**'
        - '/**'
        - '/error'
        - '/favicon.ico'
    file-upload:
      # 使用后端代理访问, 线上请使用 Nginx 配置或者直连方式，效率更高
      forward-server-url: http://127.0.0.1:9999
dax-pay:
  # 推荐只使用字母和数字, 特殊符号会导致部分通道出问题
  env: DEV
  machine-no: 60
dromara:
  # 注意, 不要设置 domain 访问路径, 自行进行拼接访问路径, 来保证可迁移性
  x-file-storage:
    default-platform: local
    # 使用Nginx映射到存储路径
    # 实际存储地址为 storage-path(存储路径) + base-path(基础路径) + 自动生成的路径(年月日) + 文件名
    local-plus:
      - platform: local
        enable-storage: true
        base-path: /file/ # 基基础存储路径 前缀和结尾都必须为 /
        storage-path: /data/files/ # 存储路径, 结尾必须为 /
    # 例如 minio地址 http://127.0.0.1:9002  桶名称 daxpay, 拼接后的地址为 http://127.0.0.1:9002/daxpay/
    minio:
      - platform: minio
        enable-storage: true
        access-key: yDAArSoyQAligC2IGf7C
        secret-key: vDgpt5R4kR2UCapMzx32Rb6qZegok21dRsU6XJ1j
        end-point: http://127.0.0.1:9002  # minio访问地址
        bucket-name: daxpay # 存储桶名称
        base-path: /file/ # 基础存储路径 前缀和结尾都必须为 /
